### ISSUE TITLE
fetch.go contains your api key

### ISSUE THREAD

**Issue by VaughnGH** [geohot/lolrecaptcha#2]
Might want to replace it when committing or load it from a .gitignore'd key file.

**Comment by Omeryl** [comment]
Did you read the README? As far as I can tell, that's the public site key for google's Recaptcha demo site ;)

**Comment by VaughnGH** [comment]
Case closed!

**Comment by geohot** [comment]
HAHAHAHAHAHA THIS IS GOLD
